/*
 * This file was automatically generated by EvoSuite
 * Mon May 15 23:11:53 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.Appt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Appt_ESTest extends Appt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Appt appt0 = new Appt(5, 5, 5, 5, 5, "org.apache.xerces.jaxp.datatype.DurationImpl", "org.apache.xerces.jaxp.datatype.DurationImpl");
      String string0 = appt0.toString();
      assertEquals("\t5/5/5 at 5:5am ,org.apache.xerces.jaxp.datatype.DurationImpl, org.apache.xerces.jaxp.datatype.DurationImpl\n", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 12, ",", "ysDF^");
      boolean boolean0 = appt0.getValid();
      assertEquals(12, appt0.getStartHour());
      assertEquals(12, appt0.getStartYear());
      assertEquals(",", appt0.getTitle());
      assertEquals(12, appt0.getStartDay());
      assertEquals(12, appt0.getStartMinute());
      assertEquals("ysDF^", appt0.getDescription());
      assertTrue(boolean0);
      assertEquals(12, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 12, ",", "ysDF^");
      String string0 = appt0.getTitle();
      assertEquals("ysDF^", appt0.getDescription());
      assertEquals(",", string0);
      assertEquals(12, appt0.getStartMonth());
      assertEquals(12, appt0.getStartHour());
      assertEquals(12, appt0.getStartYear());
      assertTrue(appt0.getValid());
      assertEquals(12, appt0.getStartDay());
      assertEquals(12, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Appt appt0 = new Appt((-2775), 0, 13, 0, 0, "0jBgU!+O9`X+~", "0jBgU!+O9`X+~");
      int int0 = appt0.getStartYear();
      assertEquals("0jBgU!+O9`X+~", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals("0jBgU!+O9`X+~", appt0.getDescription());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(13, appt0.getStartDay());
      assertEquals(-2775, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Appt appt0 = new Appt(1069, 1069, 1069, 1, 31, ", ", ", ");
      int int0 = appt0.getStartYear();
      assertEquals(", ", appt0.getTitle());
      assertEquals(1069, appt0.getStartDay());
      assertEquals(1, appt0.getStartMonth());
      assertEquals(1069, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals(", ", appt0.getDescription());
      assertEquals(31, int0);
      assertEquals(1069, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Appt appt0 = new Appt(0, 1670, 59, 1670, 1670, (String) null, "");
      int int0 = appt0.getStartMonth();
      assertEquals(59, appt0.getStartDay());
      assertEquals(1670, appt0.getStartYear());
      assertEquals(1670, appt0.getStartMinute());
      assertEquals(1670, int0);
      assertEquals(0, appt0.getStartHour());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, (-564), 0, "javax.xml.datatype.Duration#isSet(DatatypeConstants.Field field) ", "javax.xml.datatype.Duration#(getSet(DatatypeConstants.Field field)");
      int int0 = appt0.getStartMonth();
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartYear());
      assertEquals(23, appt0.getStartHour());
      assertEquals(23, appt0.getStartMinute());
      assertEquals(23, appt0.getStartDay());
      assertEquals((-564), int0);
      assertEquals("javax.xml.datatype.Duration#isSet(DatatypeConstants.Field field) ", appt0.getTitle());
      assertEquals("javax.xml.datatype.Duration#(getSet(DatatypeConstants.Field field)", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Appt appt0 = new Appt((-2775), 0, 13, 0, 0, "0jBgU!+O9`X+~", "0jBgU!+O9`X+~");
      int int0 = appt0.getStartMinute();
      assertEquals(-2775, appt0.getStartHour());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartYear());
      assertEquals(13, appt0.getStartDay());
      assertEquals("0jBgU!+O9`X+~", appt0.getDescription());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartMonth());
      assertEquals("0jBgU!+O9`X+~", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Appt appt0 = new Appt(1, 1, 1887, 1, 1, "2Gb_g,#3H)k>Lg\u0004@)b", "+X_4In:_;PoeY");
      int int0 = appt0.getStartMinute();
      assertEquals(1887, appt0.getStartDay());
      assertEquals("2Gb_g,#3H)k>Lg\u0004@)b", appt0.getTitle());
      assertEquals(1, appt0.getStartMonth());
      assertEquals(1, appt0.getStartHour());
      assertEquals(1, int0);
      assertFalse(appt0.getValid());
      assertEquals(1, appt0.getStartYear());
      assertEquals("+X_4In:_;PoeY", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 31, 11, 48, "pm", "%");
      int int0 = appt0.getStartHour();
      assertTrue(appt0.getValid());
      assertEquals(11, appt0.getStartMonth());
      assertEquals(48, appt0.getStartYear());
      assertEquals(0, int0);
      assertEquals(0, appt0.getStartMinute());
      assertEquals(31, appt0.getStartDay());
      assertEquals("pm", appt0.getTitle());
      assertEquals("%", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Appt appt0 = new Appt(104, 104, 104, 104, 104, "~T}Vpo=}|\n1CZQ", "~T}Vpo=}|\n1CZQ");
      int int0 = appt0.getStartHour();
      assertFalse(appt0.getValid());
      assertEquals("~T}Vpo=}|\n1CZQ", appt0.getDescription());
      assertEquals(104, appt0.getStartMonth());
      assertEquals(104, appt0.getStartMinute());
      assertEquals(104, int0);
      assertEquals(104, appt0.getStartYear());
      assertEquals("~T}Vpo=}|\n1CZQ", appt0.getTitle());
      assertEquals(104, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Appt appt0 = new Appt(12, 1970, 0, 2586, 23, "", "");
      int int0 = appt0.getStartDay();
      assertEquals(2586, appt0.getStartMonth());
      assertEquals(0, int0);
      assertFalse(appt0.getValid());
      assertEquals(1970, appt0.getStartMinute());
      assertEquals(12, appt0.getStartHour());
      assertEquals(23, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Appt appt0 = new Appt((-5166), (-5166), 246, (-5166), (-5166), "IgxPfBF{uN)uB7+pg", "");
      int int0 = appt0.getStartDay();
      assertEquals(246, int0);
      assertEquals("IgxPfBF{uN)uB7+pg", appt0.getTitle());
      assertFalse(appt0.getValid());
      assertEquals(-5166, appt0.getStartMinute());
      assertEquals(-5166, appt0.getStartMonth());
      assertEquals(-5166, appt0.getStartYear());
      assertEquals(-5166, appt0.getStartHour());
      assertEquals("", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Appt appt0 = new Appt(181, 181, 181, 181, 181, (String) null, (String) null);
      String string0 = appt0.getDescription();
      assertFalse(appt0.getValid());
      assertEquals(181, appt0.getStartDay());
      assertEquals(181, appt0.getStartMonth());
      assertEquals(181, appt0.getStartMinute());
      assertEquals(181, appt0.getStartHour());
      assertEquals(181, appt0.getStartYear());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Appt appt0 = new Appt(104, 104, 104, 104, 104, "~T}Vpo=}|\n1CZQ", "~T}Vpo=}|\n1CZQ");
      appt0.setDescription("aum");
      assertEquals("aum", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "]g ", "]g ");
      assertEquals("]g ", appt0.getDescription());
      
      appt0.setDescription((String) null);
      assertTrue(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Appt appt0 = new Appt(0, 1670, 59, 1670, 1670, (String) null, "");
      appt0.setTitle("");
      assertEquals(59, appt0.getStartDay());
      assertEquals(0, appt0.getStartHour());
      assertEquals(1670, appt0.getStartMonth());
      assertEquals(1670, appt0.getStartYear());
      assertEquals(1670, appt0.getStartMinute());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Appt appt0 = new Appt(0, 1670, 59, 1670, 1670, (String) null, "");
      appt0.setTitle((String) null);
      assertEquals(59, appt0.getStartDay());
      assertEquals(0, appt0.getStartHour());
      assertEquals(1670, appt0.getStartMonth());
      assertEquals(1670, appt0.getStartMinute());
      assertEquals(1670, appt0.getStartYear());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Appt appt0 = new Appt(0, 1670, 59, 1670, 1670, (String) null, "");
      String string0 = appt0.getTitle();
      assertFalse(appt0.getValid());
      assertEquals(1670, appt0.getStartMinute());
      assertEquals(0, appt0.getStartHour());
      assertEquals(1670, appt0.getStartMonth());
      assertEquals(59, appt0.getStartDay());
      assertEquals(1670, appt0.getStartYear());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Appt appt0 = new Appt((-1242), 0, (-1242), 0, 0, "--", "javax.xml.datatype.Duration#(getSet(DatatypeConstants.Field field)");
      int int0 = appt0.getStartDay();
      assertEquals("--", appt0.getTitle());
      assertEquals((-1242), int0);
      assertEquals(0, appt0.getStartYear());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartMonth());
      assertEquals(0, appt0.getStartMinute());
      assertEquals("javax.xml.datatype.Duration#(getSet(DatatypeConstants.Field field)", appt0.getDescription());
      assertEquals(-1242, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Appt appt0 = new Appt((-18), 1942, (-18), (-18), 1942, "", "");
      boolean boolean0 = appt0.getValid();
      assertEquals(1942, appt0.getStartMinute());
      assertEquals(1942, appt0.getStartYear());
      assertFalse(boolean0);
      assertEquals(-18, appt0.getStartMonth());
      assertEquals(-18, appt0.getStartDay());
      assertEquals(-18, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Appt appt0 = new Appt((-872), (-872), (-1005), (-1005), 31, "DLcq}K*", "NZ qCIMtFpxcv");
      int int0 = appt0.getStartHour();
      assertEquals(-872, appt0.getStartMinute());
      assertEquals((-872), int0);
      assertEquals(31, appt0.getStartYear());
      assertEquals(-1005, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals("NZ qCIMtFpxcv", appt0.getDescription());
      assertEquals("DLcq}K*", appt0.getTitle());
      assertEquals(-1005, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Appt appt0 = new Appt((-1324), (-1324), 1085, 1085, (-3266), "%Y%z", "");
      int int0 = appt0.getStartMinute();
      assertEquals((-1324), int0);
      assertEquals(1085, appt0.getStartMonth());
      assertEquals("%Y%z", appt0.getTitle());
      assertEquals("", appt0.getDescription());
      assertEquals(-1324, appt0.getStartHour());
      assertEquals(1085, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals(-3266, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 12, ",", "ysDF^");
      String string0 = appt0.getDescription();
      assertEquals(12, appt0.getStartHour());
      assertEquals(12, appt0.getStartMinute());
      assertEquals(12, appt0.getStartDay());
      assertEquals(",", appt0.getTitle());
      assertEquals("ysDF^", string0);
      assertEquals(12, appt0.getStartMonth());
      assertTrue(appt0.getValid());
      assertEquals(12, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "", "am");
      int int0 = appt0.getStartMonth();
      assertEquals(0, appt0.getStartMinute());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartDay());
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, int0);
      assertEquals("", appt0.getTitle());
      assertEquals(0, appt0.getStartHour());
      assertEquals("am", appt0.getDescription());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Appt appt0 = new Appt(12, 12, 12, 12, 12, ",", "ysDF^");
      String string0 = appt0.toString();
      assertNotNull(string0);
      assertEquals("\t12/12/12 at 12:12pm ,,, ysDF^\n", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Appt appt0 = new Appt((-2775), 0, 13, 0, 0, "0jBgU!+O9`X+~", "0jBgU!+O9`X+~");
      String string0 = appt0.toString();
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartMinute());
      assertEquals("0jBgU!+O9`X+~", appt0.getTitle());
      assertEquals("0jBgU!+O9`X+~", appt0.getDescription());
      assertEquals(-2775, appt0.getStartHour());
      assertEquals(0, appt0.getStartMonth());
      assertNull(string0);
      assertEquals(13, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Appt appt0 = new Appt(5, (-3232), (-3232), 0, 0, "\t", "\t");
      assertEquals("\t", appt0.getDescription());
      assertEquals(5, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartMonth());
      assertEquals("\t", appt0.getTitle());
      assertEquals(-3232, appt0.getStartMinute());
      assertEquals(-3232, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Appt appt0 = new Appt((-1), (-1), (-1), (-1684), (-1), "", (String) null);
      int int0 = appt0.getStartYear();
      assertEquals(-1, appt0.getStartHour());
      assertEquals(-1684, appt0.getStartMonth());
      assertFalse(appt0.getValid());
      assertEquals(-1, appt0.getStartMinute());
      assertEquals((-1), int0);
      assertEquals(-1, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Appt appt0 = new Appt(0, 1670, 59, 1670, 1670, (String) null, "");
      assertEquals(1670, appt0.getStartMinute());
      
      appt0.setStartMinute(59);
      assertEquals(1670, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Appt appt0 = new Appt(0, 1670, 59, 1670, 1670, (String) null, "");
      assertEquals(1670, appt0.getStartYear());
      
      appt0.setStartYear(59);
      assertEquals(59, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Appt appt0 = new Appt(0, 1670, 59, 1670, 1670, (String) null, "");
      assertEquals(59, appt0.getStartDay());
      
      appt0.setStartDay(0);
      assertEquals(1670, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Appt appt0 = new Appt(99, 99, 7, 99, 7, "YeaSC", "YeaSC");
      appt0.setStartHour(7);
      assertEquals(99, appt0.getStartMinute());
      
      appt0.setStartMinute(7);
      assertEquals(7, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Appt appt0 = new Appt(99, 99, 7, 99, 7, "YeaSC", "YeaSC");
      appt0.setStartMonth(99);
      assertEquals("YeaSC", appt0.getDescription());
      assertEquals(99, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(99, appt0.getStartMinute());
      assertEquals(7, appt0.getStartYear());
      assertEquals(7, appt0.getStartDay());
      assertEquals(99, appt0.getStartMonth());
      assertEquals("YeaSC", appt0.getTitle());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "]g ", "]g ");
      String string0 = appt0.toString();
      assertEquals("\t11/11/11 at 11:11am ,]g , ]g \n", string0);
      assertNotNull(string0);
  }
}
